[package]
name = "together"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1",features = ["tokio"] }
rfd =  "0.15.1"
chrono = "0.4.39"
image = "0.25.5"
log = "0.4.22"
env_logger = "0.11.5"

[build-dependencies]
winresource = "0.1.19"
